# Generated by Django 4.0.4 on 2022-07-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
