# Generated by Django 4.0.4 on 2022-07-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_appuser_first_name_appuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='size',
        ),
    ]
