# Generated by Django 4.0.4 on 2022-07-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_size_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='mobile',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
