# Generated by Django 4.0.4 on 2022-08-03 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart_color_cart_image_cart_price_cart_qty_cart_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pfk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
