# Generated by Django 4.0.4 on 2022-08-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_date_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default=('Pending', 'Pending'), max_length=255, null=True),
        ),
    ]
