# Generated by Django 4.0.4 on 2022-11-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_carousel_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_active',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
